eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 #     defaultZone: http://localhost:8761/eureka/


server:
  port: 8006

#spring:
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        service-name: service-consumer
#        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
#        health-check-path: /actuator/health
#        health-check-interval: 10s
#        enable: true
spring:
  application:
    name: elastic-service-test

#  cloud:
#    consul:
#      host: 49.233.70.2
#      port: 8500
#      discovery:
#        service-name: elastic-service
#        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
#        health-check-path: /actuator/health
#        health-check-interval: 10s
#        enable: true

  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    jest:
      proxy:
        host: 127.0.0.1
        port: 9200
    rest:
      uris: http://127.0.0.1:9200

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: cai
    password: cai1234
    virtual-host: /recruitment